---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 60
        timeout: 600

    - name: "install python for Ansible."
      # Your code here
      become: yes
      apt:
        name: "python3-pip"
        update_cache: yes
        state: present

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - NODE_ENV: production
    - VERSION: "1"
    - TYPEORM_CONNECTION: "postgres"
    - TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    - TYPEORM_HOST: "localhost"
    - TYPEORM_PORT: 5532
    - TYPEORM_USERNAME: "postgres"
    - TYPEORM_PASSWORD: "password"
    - TYPEORM_DATABASE: "glee"
    - TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    - TYPEORM_MIGRATIONS_DIR: "./src/migrations"

  roles:
    # Your code here
    - configure-prometheus-node-exporter
    - configure-server
