---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend app files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Run node app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "postgres"
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "database-1.cgarwfdtnt93.us-east-1.rds.amazonaws.com"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "postgres"
    TYPEORM_PASSWORD: "password"
    TYPEORM_DATABASE: "glee"
    TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    TYPEORM_MIGRATIONS_DIR: "./src/migrations"

- name: "Print message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu