---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend app files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i
    
- name: "Run backend"
  command: pm2 start npm -- start
  args:
    chdir: ~/backend-app