---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend app files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i
    
- name: "Run node app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
  environment:
    NODE_ENV: "production"
    VERSION: "{{ lookup('env','VERSION') }}"
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}" 
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"

- name: "Enable monitor"
  shell: |
    cd ~/backend-app/dist
    pm2 link 9aov2bz5u4vd37z fgvsnnx1w11hhkx
    pm2 plus

- name: "Print message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu