Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: default
      ImageId: ami-04505e74c0741db8d 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}

  EIP:
    Type: AWS::EC2::EIP
    Properties:
        InstanceId: !Ref EC2Instance
        Tags:
        - Key: Name
          Value: !Sub Elastic IP for our Server backend-${ID}
